name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV  # Ensures Python can find all modules

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest python-dotenv  # Added `python-dotenv` to fix missing module error
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify Installed Packages
        run: pip list  # Debugging step to check installed packages in GitHub Actions

      - name: Run Tests with Pytest
        run: pytest --maxfail=5 --disable-warnings  # Stops after 5 failures & hides warnings for clarity
